### ISSUE TITLE
Method [mergeRules] does not exist.

### ISSUE THREAD

**Issue by iamBiB** [MarceauKa/laravel-crudable#1]
Laravel is throwing me this

BadMethodCallException in D:\work\wwwroot7\htdocs\tifbau\vendor\laravel\framework\src\Illuminate\Validation\Validator.php line 1067: Method [mergeRules] does not exist.

Any ideea on how to fix this?

I`m using Laravel 5.4

Thank you

**Comment by MarceauKa** [comment]
Hi!
I'm working on Laravel 5.4 compatbility :)
Show me your code if you want !

**Comment by iamBiB** [comment]
i was just implementing the test to see how it would work. the snippet that you gave as an example.

**Comment by MarceauKa** [comment]
Hi again!

Just tested on the latest Laravel 5.4.3.
No problem for me...

Here's my code:

### App\Post.php
```php
namespace App;

use Akibatech\Crud\Traits\Crudable;
use Akibatech\Crud\Services\CrudFields;
use Akibatech\Crud\Fields\TextField;
use Akibatech\Crud\Fields\TinymceField;
use Akibatech\Crud\Fields\RadioField;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use Crudable;

    /**
     * @return \Akibatech\Crud\Services\CrudFields
     */
    public function getCrudFields()
    {
        return CrudFields::make([
            // Bind the title attribute to a required Text Field.
            TextField::handle('title', 'required|min:3')->withPlaceholder('Title of the post'),

            // Bind the content attribute to a Tinymce Field
            TinymceField::handle('content', 'required'),

            // Bind the status attribute to a Radio Field allowing Draft or Live options.
            RadioField::handle('status', 'required')->withOptions([0 => 'Draft', 1 => 'Live'])
        ]);
    }
}
```

### routes/web.php
```php
App\Post::crudRoutes();
```

### The migration
```php
Schema::create('posts', function (Blueprint $table) {
            $table->increments('id');
            $table->string('title');
            $table->text('content');
            $table->boolean('status')->default(0)->unsigned();
            $table->timestamps();
});
```

### The controller
Scaffolded with:
`artisan make:crud:controller PostsController Post`

**Comment by iamBiB** [comment]
Ok, i'll have a look. For now i`m dropping the idea. I need something a bit more complex that this. But i`ll surely use it for future, simpler projects. 
It`s a very good pack

**Comment by MarceauKa** [comment]
Hi again!

Package has been updated. Your bug is due to the Illuminate\Validation refactor in Laravel 5.4. The method `mergeRules` does not exist anymore. This is fixed :)

**Comment by iamBiB** [comment]
Nice. Thanks.
